// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_topics from "./routes/api/topics.ts";
import * as $index from "./routes/index.tsx";
import * as $ws_uuid_ from "./routes/ws/[uuid].ts";
import * as $CreateRoom from "./islands/CreateRoom.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/topics.ts": $api_topics,
    "./routes/index.tsx": $index,
    "./routes/ws/[uuid].ts": $ws_uuid_,
  },
  islands: {
    "./islands/CreateRoom.tsx": $CreateRoom,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
