// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_topics from "./routes/api/topics.ts";
import * as $api_topics_topicId_ from "./routes/api/topics/[topicId].ts";
import * as $index from "./routes/index.tsx";
import * as $simplechat_topicId_ from "./routes/simplechat/[topicId].tsx";
import * as $SimpleChat from "./islands/SimpleChat.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/topics.ts": $api_topics,
    "./routes/api/topics/[topicId].ts": $api_topics_topicId_,
    "./routes/index.tsx": $index,
    "./routes/simplechat/[topicId].tsx": $simplechat_topicId_,
  },
  islands: {
    "./islands/SimpleChat.tsx": $SimpleChat,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
